---
title: toddstreet | Marketing Communications Agency
url: https://www.toddstreet.com
timezone: America/New_York
collections:
  articles:
    title: Articles
    output: false
  employees:
    title: Employees
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  blog-posts:
    title: blog-posts
    output: false
  clients:
    title: clients
    output: false
  departments:
    title: departments
    output: false
  icons:
    title: icons
    output: false
  offerings:
    title: offerings
    output: false
  sections:
    title: sections
    output: false
  stats:
    title: stats
    output: false
  work:
    title: work
    output: true
  work-categories:
    title: work-categories
    output: false
defaults:
- scope:
    path: ''
    type: articles
  values:
    overview:
    images:
- scope:
    path: ''
    type: stats
  values:
    icon:
    stat-title:
    stat-description:
- scope:
    path: ''
    type: employees
  values:
    role:
    image:
    department:
- scope:
    path: ''
    type: work
  values:
    layout: job
    title:
    header:
    work-category:
    color:
    overview: false
    cover-image:
    images:
    - row:
      - file:
- scope:
    path: ''
    type: blog-posts
  values:
    overview:
    images:
- scope:
    path: ''
    type: work-overview
  values:
    work:
    -
email: smetcalf@toddstreet.com
address: 30 West 24th Street, 11th Floor
city: New York
state: New York
zip: 10010
telephone: 212.966.5900
emails:
- contact@toddstreet.com
- hr@toddstreet.com
description: 'NYC Based Marketing Communications Agency.'
plugins:
- jekyll-tidy
- jekyll-autoprefixer
- jekyll-sitemap
sass:
  style: nested
markdown: kramdown
